### ISSUE TITLE
creating  and feeding .tfrecords

### ISSUE THREAD

**Issue by robertodessi** [OpenNMT/OpenNMT-tf#184]
I have a .h5 file with features extracted from audio files.

In order to use it in OpenNMT-tf I convert it into .tfrecords file.
My model (ListenAttendSpell) on a speech translation task (working on character level) is not performing well. Even after 100k iterations the model is not learning and the translation for the dev set are minor variations (if any) of the same sentence.

An example is this:

```
U n d <space> d a s <space> i s t <space> e i n e <space> M e n s c h e n , <space> d a s s <space> w i r <space> d i e s e <space> M e n s c h e n , <space> d i e <space> d i e s e s <space> G e s c h i c h t e , <space> d a s s <space> w i r <space> d i e s e <space> M e n s c h e n , <space> d i e <space> d i e s e s <space> G e s c h i c h t e , <space> d a s s <space> e s <space> e i n e <space> M e n s c h e n , <space> d a s s <space> w i r <space> d i e s e <space> M e n s c h e n , <space> d i e <space> d i e s e s <space> G e s c h i c h t e , <space> d a s s <space>
U n d <space> d a s <space> i s t <space> e i n e <space> M e n s c h e n , <space> d a s s <space> w i r <space> d i e s e <space> M e n s c h e n , <space> d i e <space> d i e s e s <space> G e s c h i c h t e , <space> d a s s <space> w i r <space> d i e s e <space> M e n s c h e n , <space> d i e <space> d i e s e s <space> G e s c h i c h t e , <space> d a s s <space> e s <space> e i n e <space> M e n s c h e n , <space> d a s s <space> w i r <space> d i e s e <space> M e n s c h e n , <space> d i e <space> d i e s e s <space> G e s c h i c h t e , <space> d a s s <space>
U n d <space> d a s <space> i s t <space> e i n e <space> M e n s c h e n , <space> d a s s <space> w i r <space> d i e s e <space> M e n s c h e n , <space> d i e <space> d i e s e s <space> G e s c h i c h t e , <space> d a s s <space> w i r <space> d i e s e <space> M e n s c h e n , <space> d i e <space> d i e s e s <space> G e s c h i c h t e , <space> d a s s <space> e s <space> e i n e <space> M e n s c h e n , <space> d a s s <space> w i r <space> d i e s e <space> M e n s c h e n , <space> d i e <space> d i e s e s <space> G e s c h i c h t e , <space> d a s s <space>
```

I am thinking there's a problem in the data conversion/creation process.

I am using a slightly modified version of this [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/how_tos/reading_data/convert_to_records.py](url)

After reading the code for the SequenceRecordInputter class [https://github.com/OpenNMT/OpenNMT-tf/blob/d3a4ec4cfe171ad03b36233d7070e3f8f8e2c755/opennmt/inputters/record_inputter.py](url) I am creating the input files as follow:
```
def _int64_feature(time, shape):
        return tf.train.Feature(int64_list=tf.train.Int64List(value=[time, shape]))

def _float_array_feature(array):
        return tf.train.Feature(float_list=tf.train.FloatList(value=array))



for elem in input:

    rows = len(elem)
    if rows <= 8:
         print('| OUCH')
         continue
    # number of columns it is supposed to be 40 for each sample
    columns = len(elem[0])

    speech_signals = elem.flatten().tolist()

    # creating tf object that will be serialized    
    example = tf.train.Example(
        features=tf.train.Features(
            feature={
                'shape': _int64_feature(rows, columns),
                'values': _float_array_feature(speech_signals),
                 }       
            )   
    )  
    writer.write(example.SerializeToString())

```

Is this the right way to create .tfrecords data that will be used by opennmt-tf?

Thanks in advance

**Comment by guillaumekln** [comment]
Looks like this code is correct (you could also directly invoke the [`write_sequence_record`](http://opennmt.net/OpenNMT-tf/package/opennmt.inputters.record_inputter.html#opennmt.inputters.record_inputter.write_sequence_record) function from OpenNMT-tf).

How do the training and evaluation losses look like?

**Comment by robertodessi** [comment]
After 52k steps training loss is 2.3 and dev loss is 1.73

**Comment by robertodessi** [comment]
Hi, I am stuck on using ListenAttendSpell on a speech translation task.
I think the problem could be in the data creation/conversion process.
I used the model on two different dataset (one in .h5 format and one in .npz) and it seems that even after 120k steps the system is not learning at all producing the very same sentence for every input in the dev set. 

The labels file is formatted as follows:
`D a s <space> m e i n e <space> i c h <space> e r n s t , <space> t e i l w e i s e <space> d e s h a l b <space> - - <space> w e i l <space> i c h <space> e s <space> w i r k l i c h <space> b r a u c h e n <space> k a n n ! 
J e t z t <space> m u s s <space> i c h <space> m e i n e <space> S c h u h e <space> a u s z i e h e n , <space> u m <space> ü b e r h a u p t <space> a n <space> B o r d <space> z u <space> k o m m e n ! 
u n d <space> w i r <space> f u h r e n <space> s e l b s t . 
I c h <space> w e i ß , <space> f ü r <space> S i e <space> i s t <space> d a s <space> n i c h t s <space> U n g e w ö h n l i c h e s , <space> a b e r <space> . . . 
E s <space> g a b <space> e i n e <space> g a n z e <space> R e i h e <space> s o l c h e r <space> O f f e n b a r u n g e n . 
`
Does that look correct to you?

Also, do you happen to have a toy dataset (even very small) in .tfrecords that I could try or could I send you mine in order to check if it is correct?

Thanks in advance

**Comment by robertodessi** [comment]
Thanks a lot!

This is a link to the data: [https://drive.google.com/drive/folders/18SSlCzTAI9WdQPC0Jrz2NgMvrAAmn5M1?usp=sharing](url)

**Comment by robertodessi** [comment]
Thanks a lot!

This is a link to the data: https://drive.google.com/drive/folders/18SSlCzTAI9WdQPC0Jrz2NgMvrAAmn5M1?usp=sharing

**Comment by robertodessi** [comment]
Hi, any updates on this?

I tried to debug but I am stuck. I tried a different dataset and a different model and saw no difference. I thought there could be a problem in the RecordInputter and am now trying to investigate that.

**Comment by guillaumekln** [comment]
Sorry I'm a bit busy with other things at the moment. Let me know if you find more information.

> Another thing to check is whether the data are correctly aligned or not.

Did you check that?

**Comment by robertodessi** [comment]
I used a different dataset that is 100% aligned (tested on a different codebase and worked fine) and witnessed the same behaviour.

If you don't see any problem with this code to convert the data then I am assuming that the problem should be in how the input is handled (maybe the records are not accessed properly and always the same sample is read?!)

Do you know someone that used the LAS model or the SequenceRecordInputter and made it work?

```
def _int64_feature(time, shape):
        return tf.train.Feature(int64_list=tf.train.Int64List(value=[time, shape]))

def _float_array_feature(array):
        return tf.train.Feature(float_list=tf.train.FloatList(value=array))

def convert_to(read_path, write_path):
        with tf.python_io.TFRecordWriter(filename) as writer:
                with open(read_path, 'rb') as f:
                        leng = np.load(f)
                        for idx in range(leng[0]):
                                elem = np.load(f)
                                rows = len(elem)
                                cols = len(elem[0])
                                speech_signals = elem.flatten().tolist()
                                example = tf.train.Example(
                                    features=tf.train.Features(
                                          feature={
                                              'shape': _int64_feature(rows, cols),
                                              'values': _float_array_feature(speech_signals),
                                              }
                                          )
                                     )
                                writer.write(example.SerializeToString())
```

**Comment by guillaumekln** [comment]
> Do you know someone that used the LAS model or the SequenceRecordInputter and made it work?

Yes but it was several months ago so things may have changed. But it could also be a modeling issue or more commonly a configuration issue. Can you share your current training configuration?

**Comment by robertodessi** [comment]
I am running this command 

` onmt-main train_and_eval --model config/models/listen_attend_spell.py --config ../exp_code/config.yml`

And this is my configuration file

```yml
# onmt-main train_and_eval --model config/models/listen_attend_spell.py --config ../exp_code/config.yml

# The directory where models and summaries will be saved. It is created if it does not exist.
model_dir: results/LAS_2gpu

data:
  # (required for train_and_eval and train run types).
  train_features_file: /hltsrv3/rdessi/train_without_short_segments_without_first1000.tfrecords
  train_labels_file: /hltsrv3/rdessi/train_without_short_segments_without_first1000.de

  # (required for train_end_eval and eval run types).
  eval_features_file: /hltsrv3/rdessi/dev.tfrecords 
  eval_labels_file: /hltsrv3/rdessi/dev.de 

  # (optional) Models may require additional resource files (e.g. vocabularies).
  ##  source_words_vocabulary: ../data/vocab/filter_vocab.en 
  ##target_words_vocabulary: ../data/vocab/filter_vocab.de 
  target_vocabulary: /hltsrv3/rdessi/vocab.de 

# Model and optimization parameters.
params:
  # The optimizer class name in tf.train or tf.contrib.opt.
  optimizer: GradientDescentOptimizer  
  # (optional) Additional optimizer parameters as defined in their documentation.
  ##optimizer_params:
  ##  beta1: 0.8
  ##  beta2: 0.998
  learning_rate: 0.2

  # (optional) Global parameter initialization [-param_init, param_init].
  param_init: 0.1
  # (optional) Maximum gradients norm (default: None).
  clip_gradients: 1.0
  # (optional) Weights regularization penalty (default: null).
  ##regularization:
  ##  type: l2  # can be "l1", "l2", "l1_l2" (case-insensitive).
  ##  scale: 1e-4  # if using "l1_l2" regularization, this should be a YAML list.
  # (optional) Average loss in the time dimension in addition to the batch dimension (default: False).
  average_loss_in_time: true
  # (optional) The type of learning rate decay (default: None). See:
  #  * https://www.tensorflow.org/versions/master/api_guides/python/train#Decaying_the_learning_rate
  #  * opennmt/utils/decay.py
  # This value may change the semantics of other decay options. See the documentation or the code.
  decay_type: exponential_decay
  # (optional unless decay_type is set) The learning rate decay rate.
  decay_rate: 0.98
  # (optional unless decay_type is set) Decay every this many steps.
  # 1 epoch
  decay_steps: 5314
  # (optional) The number of training steps that make 1 decay step (default: 1).
  decay_step_duration: 1
  # (optional) If true, the learning rate is decayed in a staircase fashion (default: True).
  #  staircase: true
  # (optional) After how many steps to start the decay (default: 0).
  # 15 epochs
  start_decay_steps: 79710
  # (optional) Stop decay when this learning rate value is reached (default: 0).
  minimum_learning_rate: 0.00001
  # (optional) Type of scheduled sampling (can be "constant", "linear", "exponential",
  # or "inverse_sigmoid", default: "constant").
  scheduled_sampling_type: constant
  # (optional) Probability to read directly from the inputs instead of sampling categorically
  # from the output ids (default: 1).
  scheduled_sampling_read_probability: 0.9
  # (optional unless scheduled_sampling_type is set) The constant k of the schedule.
  scheduled_sampling_k: 0
  # (optional) The label smoothing value.
  label_smoothing: 0.1
  # (optional) Width of the beam search (default: 1).
  beam_width: 5
  # (optional) Length penaly weight to apply on hypotheses (default: 0).
  length_penalty: 0.2
  # (optional) Maximum decoding iterations before stopping (default: 250).
  maximum_iterations: 200
  # (optional) Replace unknown target tokens by the original source token with the
  # highest attention (default: false).
  replace_unknown_target: false

# Training options.
train:
  batch_size: 32
  
  # (optional) Batch size is the number of "examples" or "tokens" (default: "examples").
  batch_type: examples
  # (optional) Save a checkpoint every this many steps.
  save_checkpoints_steps: 5314
  # (optional) How many checkpoints to keep on disk.
  keep_checkpoint_max: 8
  # (optional) Save summaries every this many steps.
  save_summary_steps: 100
  # (optional) Train for this many steps. If not set, train forever.
  #train_steps: 500000
  # (optional) If true, makes a single pass over the training data (default: false).
  single_pass: false
  # (optional) The maximum length of feature sequences during training (default: None).
  ##  maximum_features_length: 70
  # (optional) The maximum length of label sequences during training (default: None).
  ##maximum_labels_length: 70
  # (optional) The width of the length buckets to select batch candidates from (default: 5).
  bucket_width: 1
  # (optional) The number of threads to use for processing data in parallel (default: 4).
  num_threads: 4
  # (optional) The number of elements from which to sample during shuffling (default: 500000).
  # Set 0 or null to disable shuffling, -1 to match the number of training examples.
  sample_buffer_size: -1
  # (optional) The number of batches to prefetch asynchronously. If not set, use an
  # automatically tuned value on TensorFlow 1.8+ and 1 on older versions. (default: null).
  prefetch_buffer_size: null
  # (optional) Number of checkpoints to average at the end of the training to the directory
  # model_dir/avg (default: 0).
  average_last_checkpoints: 8

# (optional) Evaluation options.
eval:
  # (optional) The batch size to use (default: 32).
  batch_size: 30
  # (optional) The number of threads to use for processing data in parallel (default: 1).
  num_threads: 1
  # (optional) The number of batches to prefetch asynchronously (default: 1).
  prefetch_buffer_size: 1
  # (optional) Evaluate every this many seconds (default: 18000).
  eval_delay: 7200
  # (optional) Save evaluation predictions in model_dir/eval/.
  save_eval_predictions: true
  # (optional) Evalutator or list of evaluators that are called on the saved evaluation predictions.
  # Available evaluators: BLEU, BLEU-detok, ROUGE
  external_evaluators: BLEU
  # (optional) Model exporter(s) to use during the training and evaluation loop:
  # last, final, best, or null (default: last).
  exporters: last

# (optional) Inference options.
infer:
  # (optional) The batch size to use (default: 1).
  batch_size: 10
  # (optional) The number of threads to use for processing data in parallel (default: 1).
  num_threads: 1
  # (optional) The number of batches to prefetch asynchronously (default: 1).
  prefetch_buffer_size: 1
  # (optional) For compatible models, the number of hypotheses to output (default: 1).
  n_best: 1

# (optional) Scoring options.
score:
  # (optional) The batch size to use (default: 64).
  batch_size: 64
  # (optional) The number of threads to use for processing data in parallel (default: 1).
  num_threads: 1
  # (optional) The number of batches to prefetch asynchronously (default: 1).
  prefetch_buffer_size: 1
```

And this is the model

```python
class ListenAttendSpell(onmt.models.SequenceToSequence):
  def __init__(self):
    super(ListenAttendSpell, self).__init__(
        source_inputter=onmt.inputters.SequenceRecordInputter(),
        target_inputter=onmt.inputters.WordEmbedder(
            vocabulary_file_key="target_vocabulary",
            embedding_size=50),
        encoder=onmt.encoders.PyramidalRNNEncoder(
            num_layers=3,
            num_units=512,
            reduction_factor=2,
            cell_class=tf.contrib.rnn.LSTMCell,
            dropout=0.5),
        decoder=onmt.decoders.MultiAttentionalRNNDecoder(
            num_layers=3,
            num_units=512,
            attention_layers=[0],
            attention_mechanism_class=tf.contrib.seq2seq.LuongAttention,
            cell_class=tf.contrib.rnn.LSTMCell,
            dropout=0.5,
            residual_connections=False))

```

**Comment by guillaumekln** [comment]
> clip_gradients: 1.0

In TensorBoard, what are the values of gradients before clipping? 1.0 seems like a small value to me.

> label_smoothing: 0.1

Maybe start without label smoothing for now.

> length_penalty: 0.2

Do we want length penalty here? It is useful for text translation but not sure about this application. Maybe start your experiments without.

> average_last_checkpoints: 8

Are your observations based on the average checkpoint?

> bucket_width: 1

If your data has a lot of possible sequence lengths, I would keep the default of 5, or even increase to 10 for this particular application.

---

Overall it can be an issue to mix too much training settings together. Try to start with fewer of them.

**Comment by robertodessi** [comment]
I have started training a model with fewer settings. I'll keep you posted

**Comment by robertodessi** [comment]
Same problem, I tried with as few settings as possible on an aligned dataset and am still getting the same translations.

Did you have the chance to try a model on that data?

**Comment by guillaumekln** [comment]
Thanks for reporting back.

I just started a training an another dataset to see if I get similar results. Maybe we should also try with a non monotic attention layer.

**Comment by robertodessi** [comment]
Sorry I forgot to mention that I indeed try with LuongAttention rather than LuongMonotonicAttention

**Comment by guillaumekln** [comment]
Thanks, that's good to know.

So I suspect something may be wrong with the `MultiAttentionalRNNDecoder` decoder. Can you try replacing it with the standard `AttentionalRNNDecoder`:

```python
onmt.decoders.AttentionalRNNDecoder(
    num_layers=4,
    num_units=512,
    bridge=onmt.layers.CopyBridge(),
    attention_mechanism_class=tf.contrib.seq2seq.LuongAttention,
    cell_class=tf.contrib.rnn.LSTMCell,
    dropout=0.3,
    residual_connections=False)
```

(And making sure that `num_layers` and `num_units` are aligned with the parameter of the encoder for the `CopyBridge` to work.)

The model is now less comparable to the paper but I'm getting very decent outputs avec 10k iterations on my data.

**Comment by robertodessi** [comment]
Thanks for your reply. I just started a training avec ( :D ) the suggested changes

**Comment by robertodessi** [comment]
What optimizer and learning rate are you using? After 10k iteration my model is not performing well. I have two trainings on two different dataset: one with 47k sample and one with 170k

**Comment by guillaumekln** [comment]
Here is the full configuration:

```python
class ListenAttendSpellV2(onmt.models.SequenceToSequence):
  def __init__(self):
    super(ListenAttendSpellV2, self).__init__(
        source_inputter=onmt.inputters.SequenceRecordInputter(),
        target_inputter=onmt.inputters.WordEmbedder(
            vocabulary_file_key="target_vocabulary",
            embedding_size=50),
        encoder=onmt.encoders.PyramidalRNNEncoder(
            num_layers=3,
            num_units=512,
            reduction_factor=2,
            cell_class=tf.contrib.rnn.LSTMCell,
            dropout=0.3),
        decoder=onmt.decoders.AttentionalRNNDecoder(
            num_layers=3,
            num_units=512,
            bridge=onmt.layers.CopyBridge(),
            attention_mechanism_class=tf.contrib.seq2seq.LuongAttention,
            cell_class=tf.contrib.rnn.LSTMCell,
            dropout=0.3,
            residual_connections=False))
```

```yml
model_dir: "run/wsj_kaldi_v2"

data:
  train_features_file: "data/wsj_kaldi/train.records"
  train_labels_file: "data/wsj_kaldi/train.txt"
  eval_features_file: "data/wsj_kaldi/test.records"
  eval_labels_file: "data/wsj_kaldi/test.txt"

  target_vocabulary: "data/wsj_kaldi/vocab.txt"

params:
  optimizer: GradientDescentOptimizer
  learning_rate: 0.2
  clip_gradients: 10.0
  scheduled_sampling_type: constant
  scheduled_sampling_read_probability: 0.9

train:
  batch_size: 32
  bucket_width: 15
  save_checkpoints_steps: 2000
  save_summary_steps: 50
  train_steps: 1000000
  sample_buffer_size: -1
  maximum_features_length: 2450
  maximum_labels_length: 330
eval:
  eval_delay: 3600
  save_eval_predictions: true
  external_evaluators: BLEU
infer:
  batch_size: 30
```

This could certainly be better but outputs appear reasonable.

**Comment by robertodessi** [comment]
Ok thanks!

I then restarted with this settings now:

```yml
model_dir: results/new_iwslt

data:
  train_features_file: /hltsrv3/rdessi/new_data/train.tfrecords
  train_labels_file: /hltsrv3/rdessi/new_data/train.char.de

  eval_features_file: /hltsrv3/rdessi/new_data/dev.tfrecords
  eval_labels_file: /hltsrv3/rdessi/new_data/dev.de

  target_vocabulary: /hltsrv3/rdessi/new_data/vocab.de 

params:
  optimizer: GradientDescentOptimizer  
  learning_rate: 0.2
  param_init: 0.1
  clip_gradients: 10.0
  average_loss_in_time: true
  scheduled_sampling_type: constant
  scheduled_sampling_read_probability: 0.9
  label_smoothing: 0.1
  beam_width: 5

train:
  batch_size: 32
  bucket_width: 15
  batch_type: examples
  save_checkpoints_steps: 5348
  keep_checkpoint_max: 2
  save_summary_steps: 100
  sample_buffer_size: 0

eval:
  batch_size: 30
  eval_delay: 7200
  save_eval_predictions: true
  external_evaluators: BLEU
  exporters: last
```

Trying one dataset with label smoothing and the other without ls.
Apart from this then the only difference with you training should be dataset size and task (speech translation vs recognition)

I'll keep you posted and thanks for your help

**Comment by robertodessi** [comment]
This is my full configuration:

```yml 
model_dir: results/new_iwslt

data:
  train_features_file: /hltsrv3/rdessi/new_data/train.tfrecords
  train_labels_file: /hltsrv3/rdessi/new_data/train.char.de

  eval_features_file: /hltsrv3/rdessi/new_data/dev.tfrecords
  eval_labels_file: /hltsrv3/rdessi/new_data/dev.de

  target_vocabulary: /hltsrv3/rdessi/new_data/vocab.de 

params:
  optimizer: GradientDescentOptimizer  
  learning_rate: 0.2
  param_init: 0.1
  clip_gradients: 10.0
  average_loss_in_time: true
  scheduled_sampling_type: constant
  scheduled_sampling_read_probability: 0.9
  label_smoothing: 0.1
  beam_width: 5

train:
  batch_size: 32
  bucket_width: 15
  batch_type: examples
  save_checkpoints_steps: 5348
  keep_checkpoint_max: 2
  save_summary_steps: 100
  sample_buffer_size: 0

eval:
  batch_size: 30
  eval_delay: 7200
  save_eval_predictions: true
  external_evaluators: BLEU
  exporters: last

```

Model:

```python
class ListenAttendSpell(onmt.models.SequenceToSequence):
  """Defines a model similar to the "Listen, Attend and Spell" model described
  in https://arxiv.org/abs/1508.01211.
  """
  def __init__(self):
    super(ListenAttendSpell, self).__init__(
        source_inputter=onmt.inputters.SequenceRecordInputter(),
        target_inputter=onmt.inputters.WordEmbedder(
            vocabulary_file_key="target_vocabulary",
            embedding_size=50),
        encoder=onmt.encoders.PyramidalRNNEncoder(
            num_layers=4,
            num_units=512,
            reduction_factor=2,
            cell_class=tf.contrib.rnn.LSTMCell,
            dropout=0.3),
        decoder=onmt.decoders.AttentionalRNNDecoder(
            num_layers=4,
            num_units=512,
            bridge=onmt.layers.CopyBridge(),
            attention_mechanism_class=tf.contrib.seq2seq.LuongAttention,
            cell_class=tf.contrib.rnn.LSTMCell,
            dropout=0.3,
            residual_connections=False))

```

After 15-20k steps  the loss is not decreasing for both datasets (3.15 for one and 2.95 for the other) and the translations are broken:

```
D i e <space> <space> e e <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e
D i e <space> <space> e e <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e
D i e <space> <space> e e <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e
D i e <space> <space> e e <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e

```

or 


```
<unk> e <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space>
<unk> e <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space>


```


Did you have the chance to try a model on the data I shared with you?
