### ISSUE TITLE
multi_source_transformation warning error

### ISSUE THREAD

**Issue by AyaNsar** [OpenNMT/OpenNMT-tf#379]
As soon as I try training the model, I get this warning error:

`tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 0 vs previous value: 0. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize.
`

and it keeps repeating itself nonstop, I never waited a lot after output message number 15, because it is really bugging seeing this message filling out the screen. 

These are the parameters I am using: 

```
  params:
  optimizer: AdamOptimizer
  learning_rate: 1.0 # The scale constant.
  clip_gradients: null
  decay_step_duration: 8 # 1 decay step is 8 training steps.
  decay_type: noam_decay_v2
  decay_params:
    model_dim: 512
    warmup_steps: 2000 # (= 16000 training steps).
  start_decay_steps: 0

```

**Comment by guillaumekln** [comment]
Are you training on CPU? This is usually the sign of a very slow training.

**Comment by AyaNsar** [comment]
I tried to run it on gpu, I get `Resource exhausted: OOM when allocating tensor with shape[512,512] Traceback (most recent call last)`

I decreased the number of batches, still was getting same error.
Could you please specify the versions of cuda, cuDNN, and tensorflow-gpu versions that is supported by OpenNMT-tf?

**Comment by Dagamies** [comment]
I have similar experiences with multi-source transformer model regarding OOM; as my sentences are quite long; I have not been able start training on GPU due OOM at all no matter what

**Comment by guillaumekln** [comment]
> Could you please specify the versions of cuda, cuDNN, and tensorflow-gpu versions that are supported by OpenNMT-tf?

OpenNMT-tf is compatible with TensorFlow 1.4 to the latest version. For CUDA and cuDNN versions, you should check the release note of each TensorFlow release.

---

Multi source training does have high memory requirements. You should probably reduce the batch size and/or the the maximum sequence length. Also, you probably need to cap both source inputs length with the following syntax:

```yaml
train:
  maximum_features_length: [100, 100]
  maximum_labels_length: 100
```

**Comment by AyaNsar** [comment]
> Multi source training does have high memory requirements. You should probably reduce the batch size and/or the the maximum sequence length. Also, you probably need to cap both source inputs length with the following syntax:
> 
> ```yaml
> train:
>   maximum_features_length: [100, 100]
>   maximum_labels_length: 100
> ```
I tried doing this, however the problem wasn't solved.

What did solve it though is that I changed the all embedding_size variables and the num_units from 512 to 256, in multi_source_transformer.py and self_attention_decoder, and it started training. BUT the original warning appeared again: 

`WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 0 vs previous value: 0. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize.
`
I even decreased the 256 to 64 but no luck. 

Here is my complete configuration:

```yaml
params:
  average_loss_in_time: true
  beam_width: 5
  clip_gradients: null
  decay_params:
    model_dim: 256
    warmup_steps: 2000
  decay_step_duration: 8
  decay_type: noam_decay_v2
  label_smoothing: 0.1
  learning_rate: 1.0
  length_penalty: 0.6
  optimizer: AdamOptimizer
  optimizer_params:
    beta1: 0.9
    beta2: 0.998
  start_decay_steps: 0
score:
  batch_size: 64
train:
  average_last_checkpoints: 8
  batch_size: 16
  batch_type: tokens
  bucket_width: 1
  effective_batch_size: 25000
  keep_checkpoint_max: 50
  maximum_features_length:
  - 80
  - 80
  maximum_labels_length: 80
  sample_buffer_size: 0
  single_pass: false
```

**Comment by guillaumekln** [comment]
```yaml
train:
  batch_size: 16
  effective_batch_size: 25000
```

With this configuration, 1 training step will accumulate the gradients of 1563 batches so the warning is expected: the training step appears "stuck" for 1563 consecutive batches.
