### ISSUE TITLE
Combining multi_source with multi_features training

### ISSUE THREAD

**Issue by penny9287** [OpenNMT/OpenNMT-tf#404]
I want to know how to deal with several input source files that each source file have more than 1 feature. Could you give me some advice ? Expect for your respond.

**Comment by guillaumekln** [comment]
Here is the section related to parallel inputs:

http://opennmt.net/OpenNMT-tf/data.html#parallel-inputs

You should provide a list of files when the model expects multiple inputs.

**Comment by penny9287** [comment]
> Here is the section related to parallel inputs:
> 
> http://opennmt.net/OpenNMT-tf/data.html#parallel-inputs
> 
> You should provide a list of files when the model expects multiple inputs.

I want to combine the multi_feature and multi_source function together, so I wonder how to deal with the source input data that each has multiple features. Thanks a lot !

**Comment by guillaumekln** [comment]
Oh ok. So this is not tested but you should try nesting the inputs:

Model input:

```python
onmt.inputters.ParallelInputter([
    onmt.inputters.ParallelInputter([
        onmt.inputters.WordEmbedder(
            vocabulary_file_key="source_1_vocabulary",
            embedding_size=300),
        onmt.inputters.WordEmbedder(
            vocabulary_file_key="source_1_feat1_vocabulary",
            embedding_size=100)],
        reducer=onmt.layers.ConcatReducer()),
    onmt.inputters.WordEmbedder(
        vocabulary_file_key="source_2_vocabulary",
        embedding_size=512)])
```

Data configuration:

```yaml
data:
  train_features_file:
    - - source_1.txt
      - source_1_feat.1.txt
    - source_2.txt

  source_1_vocabulary: ...
  source_1_feat1_vocabulary: ...
  source_2_vocabulary: ...
```
