### ISSUE TITLE
How to train an transformer-based language model

### ISSUE THREAD

**Issue by wingsyuan** [OpenNMT/OpenNMT-tf#472]
Hi,
How can I train an transformer-based language model with opennmt-tf and use this language model to calculate the perplexity of each sentence of the test set? Can you provide some examples?

Thanks a lot!!!

**Comment by guillaumekln** [comment]
Hi,

Consider the following language model definition:

https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/gpt_2.py

Depending on your hardware configuration, you might need to reduce some parameters to avoid out of memory errors. Then, your YAML configuration file `config.yml` should minimally define the training data:

```yaml
model_dir: run/lm

data:
  train_features_file: /path/to/monolingual/corpus.txt
  vocabulary: /path/to/the/vocabulary.txt
```

and the training command:

```bash
onmt-main train --model /path/to/gpt_2.py --config config.yml --auto_config
```

Finally, you can score a test set with:

```bash
onmt-main score --config config.yml --auto_config --features_file /path/to/the/test.txt
```

It will output the negative log-likelihood of each sentence.

Hope this helps getting you started.
