### ISSUE TITLE
Error when trying to use pretrained embeddings

### ISSUE THREAD

**Issue by Dagamies** [OpenNMT/OpenNMT-tf#477]
Hi,
I had following issue when trying to use pretrained embeddings (fasttext) for my model:
TypeError: Expected binary or unicode string, got {'path': '/tmp/ebm/tf/ft_a_train.vec', 'with_header': False, 'case_insensitive': False, 'trainable': True}

I had three pretrained embeddings defined:
```
model_dir: /tmp/ebm/l-512-14ck6-6r-fp16-e
data:
  train_features_file: 
    - /tmp/ebm/tf/a_train.words.txt
    - /tmp/ebm/tf/a_train.feats.txt
  train_labels_file: /tmp/ebm/tf/a_train_r.words.txt
  eval_features_file: 
    - /tmp/ebm/tf/a_validate.words.txt
    - /tmp/ebm/tf/a_validate.feats.txt
  eval_labels_file: /tmp/ebm/tf/a_validate_r.words.txt
  source_words_vocabulary: /tmp/ebm/tf/a_train.words-vocab.txt
  feature_1_vocabulary: /tmp/ebm/tf/a_train.feats-vocab.txt
  target_words_vocabulary: /tmp/ebm/tf/a_train_r.words-vocab.txt

  target_embedding:
    path: /tmp/ebm/tf/ft_a_train_r.vec
    with_header: True
    case_insensitive: False
    trainable: True
  source_embedding:
    path: /tmp/ebm/tf/ft_a_train.vec
    with_header: True
    case_insensitive: False
    trainable: True

  features_embedding:
    path: /tmp/ebm/tf/ft_a_train_f.vec
    with_header: True
    case_insensitive: False
    trainable: True

```

It turns out that in text_inputter.py there is a line on WordEmbedder.Initilize:
` self.embedding_file = metadata[self.embedding_file_key]`
-->This initializes embedding_file with "'path': '/tmp/ebm/tf/ft_a_train.vec', 'with_header': False, 'case_insensitive': False, 'trainable': True" which is not correct.

Seems to work just fine if I replace this line with following code:

```
      embedding =  metadata[self.embedding_file_key]
      if embedding is not None:
        self.embedding_file = embedding["path"]
        self.trainable = embedding.get("trainable", True)
        self.embedding_file_with_header = embedding.get("with_header", True)
        self.case_insensitive_embeddings = embedding.get("case_insensitive", True)

```
If this is correct, please integrate with code base.

**Comment by guillaumekln** [comment]
Hi,

There are currently 2 ways to configure pretrained embeddings:

## Old

In the model definition, set all required embedding arguments, e.g.:

```python
WordEmbedder(
    vocabulary_file_key="feature_1_vocabulary", 
    embedding_file_key="features_embedding",
    embedding_file_with_header=True,
    case_insensitive_embeddings=False,
    trainable=True)
```

and only pass the path in the YAML configuration:

```yaml
data:
  features_embedding: /tmp/ebm/tf/ft_a_train_f.vec
```

## New (recommended)

Do not provide the embedding configuration in the model definition, e.g.:

```python
WordEmbedder(vocabulary_file_key="feature_1_vocabulary")
```

but configure all information in the YAML configuration:

```yaml
source_2_embedding:
  path: /tmp/ebm/tf/ft_a_train_f.vec
  with_header: True
  case_insensitive: False
  trainable: True
```

About the field name in the YAML configuration:

* For single source seq2seq models you can define `target_embedding`, `source_embedding`
* For multi source/features seq2seq models you can define `target_embedding`, `source_1_embedding`, `source_2_embedding`, ..., `source_N_embedding`

---

Hope this helps.
