### ISSUE TITLE
How to set max-sentence-length while training

### ISSUE THREAD

**Issue by lqniunjunlper** [OpenNMT/OpenNMT-tf#719]

**Comment by guillaumekln** [comment]
They can be configured in the YAML file:

```yaml
train:
  maximum_features_length: 80  # Source sequences longer than this are ignored
  maximum_labels_length: 80    # Target sequences longer than this are ignored.
```

When using `--auto_config`, they are usually set to a default value. The value is reported in the training logs.
