### ISSUE TITLE
GPU OOM issue

### ISSUE THREAD

**Issue by xustev75** [OpenNMT/OpenNMT-tf#741]
# my setup:
OS: Linux version 5.4.0-48-generic (buildd@lcy01-amd64-010) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2))
GPU: GeForce GTX 1080 Ti 
GPU Memory: 11177MiB
openNMT-tf version: 2.12.1

# my training: 
onmt-main --gpu_allow_growth --model_type Transformer --config config/toy_zhen.yaml --auto_config train --with_eval

# the problem
getting out of memory error
It looks like:
1. tensorflow allocate most of GPU memory when starting up (with --gpu_allow_growth option, it started a lower allocation but soon to almost full memory
2. saved first checkpoint
3. when creating summary at 100, it tries to allocate more memory and fail

# my config 
```yaml
data:
  eval_features_file: eval/en2cn-2k.zh.tok
  eval_labels_file: eval/en2cn-2k.en.txt
  source_tokenization: config/conservative.yml
  source_vocabulary: train/news-commentary-v15.zh.vocab
  target_tokenization: config/conservative.yml
  target_vocabulary: train/news-commentary-v15.en.vocab
  train_features_file: train/news-commentary-v15.zh.tok
  train_labels_file: train/news-commentary-v15.en.tok
eval:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
infer:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
model_dir: run/
params:
  average_loss_in_time: true
  beam_width: 4
  decay_params:
    model_dim: 512
    warmup_steps: 8000
  decay_type: NoamDecay
  label_smoothing: 0.1
  learning_rate: 2.0
  num_hypotheses: 1
  optimizer: LazyAdam
  optimizer_params:
    beta_1: 0.9
    beta_2: 0.998
score:
  batch_size: 64
train:
  average_last_checkpoints: 8
  batch_size: 64
  batch_type: examples
  effective_batch_size: 10000
  keep_checkpoint_max: 8
  length_bucket_width: 1
  max_step: 20000
  maximum_features_length: 100
  maximum_labels_length: 100
  sample_buffer_size: 5000
  save_checkpoints_step: 100
  save_summary_steps: 100
```
