### ISSUE TITLE
Weighted Input

### ISSUE THREAD

**Issue by xustev75** [OpenNMT/OpenNMT-tf#743]
On the page https://opennmt.net/OpenNMT-tf/data.html, in `Weighted Inputs` section, there is instruction on how to use weighted input. 
```
data:
  train_features_file:
    - domain_a.en
    - domain_b.en
    - domain_c.en
  train_labels_file:
    - domain_a.de
    - domain_b.de
    - domain_c.de
  train_files_weights:
    - 0.5
    - 0.2
    - 0.3
```
But it seems like that custom model is needed to be able to do this. There is no related example. Can someone help please?

Thanks,

**Comment by guillaumekln** [comment]
If by "custom model" you mean a model taking 2 inputs, each element in `train_features_file` should have 2 files. For example:

```yaml
data:
  train_features_file:
    - - domain_a.input1.en
      - domain_a.input2.en
    - - domain_b.input1.en
      - domain_b.input2.en
  train_labels_file:
    - domain_a.de
    - domain_b.de
  train_files_weights:
    - 0.8
    - 0.2
```
