### ISSUE TITLE
Running sequence tagger using OpenNMT-tf

### ISSUE THREAD

**Issue by faysalhossain2007** [OpenNMT/OpenNMT-tf#939]
I am able to run the Transformer model using OpenNMT-tf by executing the following script:

`onmt-main --model_type Transformer --config data.yml --auto_config train --with_eval`

In the [documentation](https://opennmt.net/OpenNMT-tf/package/opennmt.models.html), I can see that OpenNMT provide SequenceTagger model. But When I run the following command it shows me an error stating model_type sequencetagger  is not available.

`onmt-main --model_type SequenceTagger --config data.yml --auto_config train --with_eval`

In data.yml file I provide the following settings:

```
model_dir: run/

data:
  train_features_file: src-train.txt
  train_labels_file: tgt-train.txt
  eval_features_file: src-val.txt
  eval_labels_file: tgt-val.txt
  source_vocabulary: src-vocab.txt
  target_vocabulary: tgt-vocab.txt
train:
  max_step: 50
  batch_size: 256
```

How to run the sequence tagger using OpenNMT -tf?
